export const MOCK_BRIEFING = {
  articles: [
    {
      id: 'openai-gpt5-marketing-shift',
      headline: 'OpenAI\'s <em>GPT-5 launch</em> redraws the AI assistant market overnight',
      deck: 'With reasoning scores 40% above GPT-4o and a $20/month price hold, every competitor\'s roadmap just became a liability.',
      category: 'Competitor Move',
      source: 'The Verge',
      url: 'https://www.theverge.com',
      timeAgo: '1h ago',
      readTime: '4 min',
      isLead: true,
    },
    {
      id: 'google-pmax-creative-ai',
      headline: 'Google\'s Performance Max gets <em>generative creative</em> — and it\'s live in all accounts',
      deck: 'Advertisers can now let Google auto-generate display and video assets from a URL. Early tests show a 15% CTR lift, but brand control is limited.',
      category: 'AI Tool',
      source: 'Marketing Week',
      url: 'https://www.marketingweek.com',
      timeAgo: '3h ago',
      readTime: '3 min',
      isLead: false,
    },
    {
      id: 'tiktok-b2b-ad-formats',
      headline: 'TikTok quietly launches <em>B2B ad targeting</em> to challenge LinkedIn',
      deck: 'Job title, company size, and industry signals are now available in TikTok Ads Manager — a direct shot at LinkedIn\'s $4.7bn ad business.',
      category: 'Industry Trend',
      source: 'TechCrunch',
      url: 'https://techcrunch.com',
      timeAgo: '5h ago',
      readTime: '3 min',
      isLead: false,
    },
    {
      id: 'canva-enterprise-brand-kit',
      headline: 'Canva\'s enterprise brand kit now enforces <em>AI guardrails</em> at scale',
      deck: 'New admin controls let brand managers lock fonts, colours, and tone-of-voice — preventing rogue AI-generated content from breaking guidelines.',
      category: 'New Tool',
      source: 'Product Hunt',
      url: 'https://www.producthunt.com',
      timeAgo: '6h ago',
      readTime: '2 min',
      isLead: false,
    },
    {
      id: 'apple-search-ads-expansion',
      headline: 'Apple Search Ads expands to <em>50 new markets</em> with first-party audience data',
      deck: 'The rollout brings Apple\'s privacy-safe targeting to emerging markets just as Meta\'s ATT losses mount — worth testing now before CPMs inflate.',
      category: 'Campaign Intel',
      source: 'Wired',
      url: 'https://www.wired.com',
      timeAgo: '8h ago',
      readTime: '3 min',
      isLead: false,
    },
    {
      id: 'forrester-b2b-content-report',
      headline: 'Forrester: <em>72% of B2B buyers</em> ignore vendor content entirely in 2025',
      deck: 'New research shows peer communities and dark social now drive more pipeline than brand content — the playbook every marketing team runs is officially broken.',
      category: 'Research',
      source: 'Hacker News',
      url: 'https://news.ycombinator.com',
      timeAgo: '10h ago',
      readTime: '5 min',
      isLead: false,
    },
  ],
  digest: {
    summary: '<strong>AI is collapsing the cost of creative production</strong> faster than most marketing teams can adapt their governance. Google\'s PMax update and Canva\'s guardrails signal that the real battleground is now <strong>brand control inside AI tooling</strong>, not output quality.',
    detail: 'Meanwhile, the TikTok B2B play and Apple Search Ads expansion point to a fragmentation of the upper funnel — channels that didn\'t exist in your media mix two years ago are now table stakes. The Forrester data is the loudest signal: if buyers have already tuned out brand content, the question isn\'t what to publish, it\'s <strong>where the conversation is actually happening</strong>.',
    watchFor: 'Watch for Google\'s response to GPT-5 — a Gemini price cut or PMax feature drop in the next 72 hours is likely.',
  },
  fetchedAt: new Date().toISOString(),
  sourceCount: 48,
}
