export const MOCK_FOR_YOU = {
  team: {
    name: 'Marketing',
    tools: ['HubSpot', 'Canva', 'Google Ads', 'Meta Business Suite'],
    watching: ['Jasper AI', 'Adobe Express', 'Salesforce Marketing Cloud'],
    stakeholders: ['Sales Team', 'CMO Office', 'Agency Partners'],
  },
  articles: [
    {
      id: 'hubspot-ai-sequences',
      headline: 'HubSpot\'s <em>AI sequence builder</em> lands in every Marketing Hub tier',
      deck: 'Previously locked to Sales Hub, AI-written email sequences are now in your marketing workflows. Time to audit your nurture campaigns before competitors do.',
      category: 'AI Tool',
      source: 'TechCrunch',
      url: 'https://techcrunch.com',
      timeAgo: '2h ago',
      readTime: '3 min',
      signal: 'Tool you use',
      signalDetail: 'HubSpot',
    },
    {
      id: 'meta-advantage-creative',
      headline: 'Meta Advantage+ now tests <em>150 creative variants</em> automatically',
      deck: 'Automated creative A/B testing is live across all accounts. Your campaign managers should review Meta\'s new budget-reallocation logic before this week\'s reporting cycle.',
      category: 'Campaign Intel',
      source: 'Marketing Week',
      url: 'https://www.marketingweek.com',
      timeAgo: '4h ago',
      readTime: '4 min',
      signal: 'Ad platform',
      signalDetail: 'Meta Business Suite',
    },
    {
      id: 'jasper-brand-voice-clone',
      headline: 'Jasper AI launches <em>enterprise brand voice cloning</em> — a direct HubSpot threat',
      deck: 'Jasper trains a brand voice model from your existing content library, potentially replacing HubSpot\'s AI writing assistant for larger teams. Evaluate before renewal.',
      category: 'Competitor Move',
      source: 'The Verge',
      url: 'https://www.theverge.com',
      timeAgo: '6h ago',
      readTime: '3 min',
      signal: 'Watching',
      signalDetail: 'Jasper AI',
    },
    {
      id: 'canva-generative-video',
      headline: 'Canva ships <em>generative video</em> inside the brand editor',
      deck: 'B-roll, product shots, and social clips can now be generated in Canva\'s existing workflow — no Runway subscription needed. Review your agency retainer scope before this hits your plan.',
      category: 'New Tool',
      source: 'Product Hunt',
      url: 'https://www.producthunt.com',
      timeAgo: '8h ago',
      readTime: '2 min',
      signal: 'Tool you use',
      signalDetail: 'Canva',
    },
    {
      id: 'gartner-cmo-spend-2025',
      headline: 'Gartner: <em>AI content budgets tripling</em> while headcount stays frozen until 2026',
      deck: 'AI tooling now takes 31% of content budgets as FTE hiring stalls. This is the data your CMO will bring to the next planning cycle — get ahead of the conversation.',
      category: 'Research',
      source: 'Wired',
      url: 'https://www.wired.com',
      timeAgo: '12h ago',
      readTime: '5 min',
      signal: 'Stakeholder',
      signalDetail: 'CMO Office',
    },
  ],
}
